conditioning:
  method: ps
  # method: fista
  params:
    scale: 2

data:
  name: recon
  accs:
    - 20
    - 4
    - 8
    - 12
    - 16
    - 24
  masks: 
    - ktGaussian
    - ktRadial
    - ktUniform
  datapath: /home/anurag/Code/dps-mc/ValDatasetCine.json
  # datapath: /home/anurag/Code/notebooks/PaperValDataCine.json
  mask_path: /bigdata/CMRxRecon2024/ChallengeData/MultiCoil/CONTRAST_TYPE/ValidationSet/Mask_Task2/
  # mask_path: /bigdata/CMRxRecon2024/ChallengeData/MultiCoil/CONTRAST_TYPE/TrainingSet/Mask_Task2/
  single_file_eval: true
  dest_dir: /bigdata/CMRxRecon2024/ChallengeVal/
  # dest_dir: /bigdata/CMRxRecon2024/ChallengeTest/
  input: /input
  output: /output

measurement:
  operator:
    name: recon
  
  noise: 
    name: gaussian
    sigma: 0.05