conditioning:
  method: ps
  # method: fista
  params:
    scale: 2

data:
  name: recon
  accs:
    - 4
    - 12
    - 24
  masks: 
    - ktGaussian
    - ktRadial
    - ktUniform
  datapath: /home/anurag/Code/notebooks/PaperValDataCine.json
  mask_path: /bigdata/CMRxRecon2024/ChallengeData/MultiCoil/CONTRAST_TYPE/TrainingSet/Mask_Task2/
  single_file_eval: true
  dest_dir: /bigdata/CMRxRecon2024/ValResults/test/

measurement:
  operator:
    name: recon
  
  noise: 
    name: gaussian
    sigma: 0.05