conditioning:
  method: ps
  # method: fista
  params:
    scale: 2

data:
  name: recon
  root: /bigdata/CMRxRecon2024/ChallengeData/MultiCoil/Cine/TrainingSet/FullSample/P011/cine_sax.mat
  mask_path: /bigdata/CMRxRecon2024/ChallengeData/MultiCoil/Cine/TrainingSet/Mask_Task2/P011/
  us_mask_type: ktGaussian4
  single_file_eval: true

measurement:
  operator:
    name: recon
  
  noise: 
    name: gaussian
    sigma: 0.05